### ISSUE TITLE
Data outdated

### ISSUE THREAD

**Issue by coveritytest** [GrovesD2/market_monitor_trend_dash#1]
Not to be a pain, but the csv data is out of date.

**Comment by coveritytest** [comment]
Hmm, yet again the data is old although Market Monitor data is up to date. What is the reason?

**Comment by GrovesD2** [comment]
I have to manually update the data (and I have been away the last few days!)

I would look into automating this process - but more people would have to be using the dashboard for me to invest time into that. As far as I can see, only 3 people use it every day. The original intention for the dash/outputs is for research only - not live trading.

I'll likely update the data tomorrow once I'm back to my laptop!

**Comment by coveritytest** [comment]
If you want, I would volunteer to keep the data up-to-date! It's interesting to see how this develops. If you want to tell me how to update the data, please tell me how I can contact you. Cheers!
